### ISSUE TITLE
Create background job to cleanup BlacklistedTokens

### ISSUE THREAD

**Issue by chris-t-li** [Fantasy-Fit/fantasy-fit-web#134]
Currently, on user logout, a BlacklistedToken is created so that subsequence use of the token will be rejected by authentication.

However, there is no cleanup process that destroys expired tokens. 

Need to create a background task that will run [daily] that will destroy expired tokens
![Screen Shot 2023-05-10 at 11 03 13 AM](https://github.com/Fantasy-Fit/fantasy-fit-web/assets/111921809/44c903f2-f4a7-46c3-959f-2d6369d2c9dc)

**Comment by alexistorosina1** [comment]
this must mean that some expired tokens arent being deleted. I believe there is a background task is being ran everyday at 4:30am

**Comment by chris-t-li** [comment]
Maybe is here, in models/blacklisted_token.rb

Should it be "destroy_all" instead of "delete_all"? .

```
class BlacklistedToken < ApplicationRecord
    belongs_to :user

    def self.delete_expired_tokens
        self.where("expires_at < ?", Time.current).delete_all
    end
end
```

**Comment by alexistorosina1** [comment]
will check it out
