### ISSUE TITLE
Error 401 uncaught in promise when trying to make a comment on a tournament

### ISSUE THREAD

**Issue by dovid11564** [Fantasy-Fit/fantasy-fit-web#142]
Came across this issue when trying to comment on a tournament. 
![image](https://github.com/Fantasy-Fit/fantasy-fit-web/assets/110751525/87252973-f244-4573-b67e-7bdf64591e39)

I spoke to @chris-t-li, we thought it might be a JWT token issue. Since I had auto logged in and auto refresh for JWT token was missing, therefore I was getting unauthorized. Logging out and logging back in again did not solve the issue, so I am not sure what the issue might be.

**Comment by chris-t-li** [comment]
@dovid11564 Can you please expand the error message in the Uncaught promise? What is the data value? {status: 401, data: {...}}?

**Comment by dovid11564** [comment]
I havn't actually been able to replicate this. It seems like it might have been JWT or sessions expiring in the end.

**Comment by chris-t-li** [comment]
@dovid11564 can I close this issue for now? If you can replicate, feel free to create a new issue.
