### ISSUE TITLE
Auth does not redirect to login page after JWT has expired

### ISSUE THREAD

**Issue by chris-t-li** [Fantasy-Fit/fantasy-fit-web#146]
After JWT expiry, and user tries to login. The authentication fails because token has expired. However, user is not redirected to login page when this occurs.

![Screen Shot 2023-05-25 at 10 41 41 AM](https://github.com/Fantasy-Fit/fantasy-fit-web/assets/111921809/407add0f-54a7-4e6c-a75e-311903c8155d)
<img width="697" alt="Screen Shot 2023-05-25 at 10 41 26 AM" src="https://github.com/Fantasy-Fit/fantasy-fit-web/assets/111921809/2e3f38ff-ac3c-4b34-84e0-632f9d60785d">

**Comment by Hasrivastav** [comment]
Hello there! I would like to contribute to this project and work on the "Auth does not redirect to login page after JWT has expired" issue.  
 I have experience with authentication systems and handling JWTs, and I believe I can help address this problem.

**Comment by chris-t-li** [comment]
I have assigned this to you. Please create a new branch to work on. When you are ready, create a PR for review.

Some notes on how I intend to address this issue:
* When user first logs in, a token and refresh token shall be created and stored in cookies;
* Token shall have expiration of [3] days and refresh token [30] days;
* When the application loads, it should try to auto-login by using token;
* If token has expired, then it shall try to use refresh token to authenticate;
* On logout, both token and refresh tokens shall be blacklisted
