### ISSUE TITLE
User should not be able to delete posts from other users

### ISSUE THREAD

**Issue by chris-t-li** [Fantasy-Fit/fantasy-fit-web#54]
A user should only be able to delete a post that they create themselves
Users should not be able to remove any post from others
![Screen Shot 2023-04-20 at 10 54 57 AM](https://user-images.githubusercontent.com/111921809/233405233-1e6de51d-9bc7-4a2a-b0e6-2c15f3eb3a03.png)

**Comment by dkussainov** [comment]
fixed with #71
